name: Linting

on:
  pull_request:
    types: [ opened, synchronize, reopened, ready_for_review ]
  pull_request_target:
    types: [ opened, synchronize, reopened, ready_for_review ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

jobs:
  linters:
    name: Linters
    # If the PR is coming from a fork (pull_request_target), ensure it's opened by "dependabot[bot]".
    # Otherwise, clone it normally.
    if: github.event_name != 'pull_request_target' || github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        if: github.event_name != 'pull_request_target' || github.actor == 'dependabot[bot]'
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
        with:
          fetch-depth: 0

      - name: Dependabot Checkout
        if: github.event_name == 'pull_request_target'
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Check for Changes
        uses: dorny/paths-filter@v3.0.2
        id: changes
        with:
          filters: |
            source_code:
              - '**/src/**'
              - '**/Dockerfile'
              - '**/build.gradle.kts'
            docs:
              - README.md
              - 'docs/**'

      - name: Lint Documents
        if: steps.changes.outputs.docs == 'true'
        uses: avto-dev/markdown-lint@v1.5.0
        with:
          config: './config/markdown-lint/rules.json'
          args: '**/*.md'

      - name: Install Java
        if: steps.changes.outputs.source_code == 'true'
        uses: actions/setup-java@2dfa2011c5b2a0f1489bf9e433881c92c1631f88
        with:
          java-version: 21
          distribution: 'temurin'

      - name: Setup Gradle
        if: steps.changes.outputs.source_code == 'true'
        uses: gradle/actions/setup-gradle@v4
        env:
          GITHUB_TOKEN: ${{ secrets.REVIEWER_TOKEN }}

      - name: Check Style
        if: steps.changes.outputs.source_code == 'true'
        id: spotless
        env:
          GITHUB_TOKEN: ${{ secrets.REVIEWER_TOKEN }}
        run: ./gradlew spotlessCheck
